language: java
sudo: false
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

jobs:
  include:
#    - stage: test
#      script: mvn test cobertura:cobertura
#      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: push-images
      script: mvn package -DskipTests && cd skip-the-dishes-command && mvn dockerfile:build dockerfile:push -DskipTests
#      on:
#        tags: true
