language: java
sudo: false

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: test
      script:
        - mvn test cobertura:cobertura
      after_success:
        - bash <(curl -s https://codecov.io/bash)
