language: java
sudo: false

cache:
  directories:
  - $HOME/.m2

jobs:
  include:
    - stage: test
      jdk:
        - oraclejdk8
      script:
        - mvn test cobertura:cobertura
      after_success:
        - bash <(curl -s https://codecov.io/bash)
