version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=skip_the_dishes
      - POSTGRES_USER=skip_the_dishes
      - POSTGRES_PASSWORD=skip_the_dishes
      - MAX_CONNECTIONS=300

  event-store:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
