version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=skip_the_dishes
      - POSTGRES_USER=skip_the_dishes
      - POSTGRES_PASSWORD=skip_the_dishes
      - MAX_CONNECTIONS=300

  postgres-security:
    image: postgres:9.6
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=skip_the_dishes_security
      - POSTGRES_USER=skip_the_dishes_security
      - POSTGRES_PASSWORD=skip_the_dishes_security
      - MAX_CONNECTIONS=300

  event-store:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"

  skip-command:
    image: skip/command-app
    volumes:
      - .:/home/application
    command: ["/home/application/wait-services.sh"]
    build: skip-the-dishes-command/
    environment:
      - EVENT_STORE_URL=http://event-store:2113
      - CONFIG_RESOURCE=-Dconfig.resource=file:/home/application/docker-event-store.conf
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - event-store

  skip-query:
    image: skip/query-app
    volumes:
      - .:/home/application
    command: ["/home/application/wait-services.sh"]
    build: skip-the-dishes-query/
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/skip_the_dishes
      - EVENT_STORE_URL=http://event-store:2113
      - CONFIG_RESOURCE=-Dconfig.resource=file:/home/application/docker-event-store.conf
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - event-store

  skip-security:
    image: skip/security-app
    volumes:
      - .:/home/application
    command: ["/home/application/wait-services.sh"]
    build: skip-the-dishes-security-application/
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-security:5432/skip_the_dishes_security
    ports:
      - "8083:8083"
    depends_on:
      - postgres-security
