version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=skip_the_dishes
      - POSTGRES_USER=skip_the_dishes
      - POSTGRES_PASSWORD=skip_the_dishes
      - MAX_CONNECTIONS=300

  event-store:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order_events:1:1"
    depends_on:
      - zookeeper

  keycloak:
    image: jboss/keycloak:3.4.3.Final
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: changeit
