version: '2'
services:
  postgres:
    image: timnn/postgres-multi:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERS=skip_the_dishes_user:skip_the_dishes_pass
      - POSTGRES_DATABASES=keycloak:skip_the_dishes_user|skip_the_dishes_order:skip_the_dishes_user
      - MAX_CONNECTIONS=100

  event-store:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"

  keycloak:
    image: jboss/keycloak:4.0.0.Final
    ports:
       - "8080:8080"
    command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/config", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"]
    volumes:
       - ./docs/keycloak:/opt/jboss/keycloak/config
    environment:
       - KEYCLOAK_USER=admin
       - KEYCLOAK_PASSWORD=admin
       - DB_ADDR=postgres
       - DB_PORT=5432
       - DB_VENDOR=POSTGRES
       - DB_DATABASE=keycloak
       - DB_USER=skip_the_dishes_user
       - DB_PASSWORD=skip_the_dishes_pass
    depends_on:
      - postgres

  skip-command:
    image: skip/command-app
    volumes:
      - .:/home/application
    command: ["/home/application/wait-services.sh"]
    build: skip-the-dishes-command/
    environment:
      - EVENT_STORE_URL=http://event-store:2113
      - CONFIG_RESOURCE=-Dconfig.resource=file:/home/application/docker-event-store.conf
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - event-store

  skip-query:
    image: skip/query-app
    volumes:
      - .:/home/application
    command: ["/home/application/wait-services.sh"]
    build: skip-the-dishes-query/
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/skip_the_dishes_order
      - EVENT_STORE_URL=http://event-store:2113
      - CONFIG_RESOURCE=-Dconfig.resource=file:/home/application/docker-event-store.conf
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - event-store
