spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skip_the_dishes
    username: skip_the_dishes
    password: skip_the_dishes
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:config/liquibase/master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  h2:
    console:
      enabled: true
