# Datasource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skip_the_dishes_order
    username: skip_the_dishes_user
    password: skip_the_dishes_pass
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

# Keycloak
keycloak:
  auth-server-url: http://keycloak:8080/auth
  credentials:
    secret: 3bfdaad0-38d6-45f4-a01b-fb455cf28ff4

# Event Store
event:
  store:
    user: admin
    password: changeit
    url: http://localhost:2113
