spring:
  profiles:
    active: local
  application:
    name: Skip the Dishes - Order (Query)

# Server
server:
  version: @project.version@
  port: 8082

# Constraints
skip:
  publicConstraints:
    - pattern: /**
      methods: OPTIONS
  constraints:
    - pattern: /api/v1/product/**
      roles:
        - role: PRODUCT
          methods:
            - GET
    - pattern: /api/v1/order/**
      roles:
        - role: ORDER
          methods:
            - GET
