# Event Store
event:
  store:
    user: admin
    password: changeit
    url: http://localhost:2113
  sourcing:
    subscribe: 2

# Security
security:
  oauth2:
    resource:
      jwt:
        key-value: |
           -----BEGIN PUBLIC KEY-----
           MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv0b9r3G/sYmhSHH3/Vsr
           sP2RoxFUwygbwSrNHaamlHUhYtvGv7Vx+IC6gV2f+bSYvEiiqUfnHageUZrgSP3O
           +DCgWD7rIjfU0GoBM3NOZfRKG7/A0hQ/Kdzac/ZgNWFj/OdM6lWYEAsf02eYZ92Y
           zJjrlaLkDrnuTOJnla2JnAmhpVVoLA5ynuqKspgCA9XoiE3Fsf4WDnhTr69f8RjJ
           LaOem+hdVZdwja/MtUNBcQmNl7NOaPWTlikPmboys8OzW7FTcEJvqEkKu7B0KmET
           Qve4q7h2kPIxdvFbeUoyrfaw2HL/9PKO5vtgEInDH3cuiQ2IPXIDhBNKLTWdZPq4
           DQIDAQAB
           -----END PUBLIC KEY-----
