# Event Store
event:
  store:
    user: admin
    password: changeit
    url: http://localhost:2113

# Keycloak
keycloak:
  auth-server-url: http://localhost:8080/auth
  credentials:
    secret: 3bfdaad0-38d6-45f4-a01b-fb455cf28ff4
